# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('guests', models.ManyToManyField(null=True, related_name='guest_trips', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
